# a mybinder.org-ready environment for demoing jupyterlab-transformers-completer
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-transformers-completer-demo
#
name: jupyterlab-transformers-completer-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10,<3.11.0a0
  - jupyterlab >=4.1.0,<5
  - jupyterlab_server >=2.25.2
  # lab dev
  - hatch
  - build
  # labextension build dependencies
  - nodejs >=18,<19
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
